### ISSUE TITLE
[BUG] : Able to change the text which shouldn't be changed.

### ISSUE THREAD

**Issue by sahith29s** [hiteshchoudhary/devui#12]
### how to reproduce 

1. Set up the project locally.
2. Then go to "http://localhost:3000/templates/chat".
3. Select the " Select a page UI".
4. Then type something , and you will be able to change the text.
5. Another issue is after changing the text you cannot select any other "Page UI".

### video

[Screencast from 09-20-2023 09:15:22 AM.webm](https://github.com/hiteshchoudhary/devui/assets/116652852/1725ab7e-be70-4b9b-9f8d-d3c34b9ebfb8)

**Comment by deepesh-dg** [comment]
Hello @sahith29s,

Dropdown button is behaving like a search-box and it should be editable in order to search any page in a particular template.

To get all list of pages, you will need to clear the search box.
