### ISSUE TITLE
Padding for both end is not same

### ISSUE THREAD

**Issue by musiur** [hiteshchoudhary/devui#9]
https://devuiv2.vercel.app/templates/chat

![image](https://github.com/hiteshchoudhary/devui/assets/99522246/283919a6-221d-47be-9e8f-a9f600dd5f11)
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/4700c401-8512-4ffb-b43a-7359743cf137)

**Comment by Shivam-fibo** [comment]
Assign me this task. I will do it with the help of CSS padding inline property (if it work otherwise there are plenty of others method to do this work)

**Comment by sahith29s** [comment]
I want to work on this issue, Can anyone assign me this task?

**Comment by musiur** [comment]
@sahith29s @Shivam-fibo 
- Please fork this repo into your own account. 
- Setup in your machine and update or fix the issue. 
- Push to your repo and come back to here to create a new pull request like this.
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/fb65df94-4a46-43fc-9c5e-5785b69e863d)
 
- Then select fork option to create pull request and set your account's repo at from select.
- Finally create pull request. Maintainer will update and will give you feedback if needed.

Happy coding!

**Comment by sahith29s** [comment]
Hey bro can you please help me I just solved the issue.
since I  am new to open source I don't know how to pull the request.

**Comment by musiur** [comment]
Okay! have you forked or cloned? @sahith29s

**Comment by sahith29s** [comment]
Yes, I resolved the issue as well. @musiur

**Comment by sahith29s** [comment]
My bad I cloned the repo, sorry.

**Comment by sahith29s** [comment]
Bro can you please guide me , If I can make this it will my first open source contribution.

**Comment by musiur** [comment]
Okay! Just fork like this:

![image](https://github.com/hiteshchoudhary/devui/assets/99522246/e9799104-c693-45e2-a492-7b20837fc808)

![image](https://github.com/hiteshchoudhary/devui/assets/99522246/0cabc97c-993c-473b-88b2-3460d6fa5480)

![image](https://github.com/hiteshchoudhary/devui/assets/99522246/a7deb509-07a5-4d4f-9791-89310b8f819d)

![image](https://github.com/hiteshchoudhary/devui/assets/99522246/3cb2951a-05e1-4e71-8062-9c1211b68476)

Then make changes and push your code into your remote repository.

After that - 

Do this 
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/6ba5ad3e-b1c0-4649-9b53-1bee1b5f11b1)
or,
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/95534c04-bdb9-4d67-b377-b2ce972c815c)
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/afd06531-b3fa-4c6b-b6cb-0d4a4cf43d36)
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/ab44140e-6c82-464b-89fa-0a4c8a0a123f)
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/e8c493b0-2dc5-49cc-9f52-75e47ac21fee)
![image](https://github.com/hiteshchoudhary/devui/assets/99522246/9c4a8f07-bab8-4246-85a5-1e58cf57d99b)

Here in next step You will have button to create pull request instead of view as in this picture. Because I have already created a pull request.

![image](https://github.com/hiteshchoudhary/devui/assets/99522246/8a4ffcdb-5443-4a92-8af3-a473b978aa1b)

Try this brother!

**Comment by musiur** [comment]
You can follow this playlist on YouTube: [OpenSource Tutorial Playlist - Piyush Garg](https://www.youtube.com/playlist?list=PLinedj3B30sBsmRRL8XyTGadjRGkzRPb7)

**Comment by sahith29s** [comment]
Thank you a lot dude. @musiur

**Comment by sahith29s** [comment]
Is there any things wrong in my pull request , I have made it 2 weeks ago and still haven't yet got merged ?
